services:
  db:
    container_name: systemzero-postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./api/data/postgres:/data/postgress
      - ./api/scripts/docker-db/:/docker-entrypoint-initdb.d
    